using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

namespace FractalGenerator
{
    /// <summary>
    /// An abstract class for objects which generate fractals.
    /// </summary>
    public abstract class FractalGenerator
    {
        /// <summary>
        /// Creates the fractal using the specified width and height.
        /// </summary>
        /// <param name="width">The width.</param>
        /// <param name="height">The height.</param>
        /// <returns>An image containing the generated fractal.</returns>
        public abstract Image Create(int width, int height);

        /// <summary>
        /// Gets or sets the concurrency mode of the fractal generation.
        /// </summary>
        /// <value>The mode.</value>
        public ConcurrencyMode Mode
        {
            get;
            set;
        }

        /// <summary>
        /// Gets the name of the fractal generated by this fractal generator.
        /// This is equivalent to the static FractalType property and is
        /// provided as an instance property as a convenience.
        /// </summary>
        /// <value>The name.</value>
        public virtual string FractalType
        {
            get
            {
                return this.GetType().Name;
            }
        }
    }
}
